# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-15 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiped',
            options={'get_latest_by': 'time'},
        ),
    ]
